### PR TITLE
Update reproducible build docs to instruct user to sets the right release

### PR DESCRIPTION
**Pull request by newtonick**
0.8.5 made changes to the dev branch that make 0.8.0 no reproducible unless you know to checkout the 0.8.0 brach/tag. This PR adds documentation to provide instructions on checking out the correct branch.

### CODE REVIEW

**Comment by kdmukai** [comment]
In the following section (the macOS/linux instructions and the Windows instructions) we have the user define a `RELEASE_TAG` env var so we may as well reuse that. Just have to move the `git checkout` command into the macOS/linux and Windows sections:

```bash
# in the macOS/linux section:
git checkout $RELEASE_TAG
```

```powershell
# in the Windows section:
git checkout $env:RELEASE_TAG
```

**Comment by kdmukai** [comment]
Regardless of my suggestion above, ACK for any approach to convey this key step.

**Comment by newtonick** [comment]
> In the following section (the macOS/linux instructions and the Windows instructions) we have the user define a `RELEASE_TAG` env var so we may as well reuse that. Just have to move the `git checkout` command into the macOS/linux and Windows sections:
> 
> ```shell
> # in the macOS/linux section:
> git checkout $RELEASE_TAG
> ```
> 
> ```powershell
> # in the Windows section:
> git checkout $env:RELEASE_TAG
> ```

The main reason I didn't use the RELEASE_TAG was because of the *nix vs Windows difference. If I move the `git checkout` I think it would be important to move the `git submodule init` and `git submodule update`. I'll make this update and if it flows more logically.

**Comment by kdmukai** [comment]
Reiterating my ACK!

**Pull request merged**
