### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by newtonick**
- [x] Reorganized
- [x] Add docker and docker-compose dependency information
- [x] Build instructions for building a specific board
- [x] Dev build configs
- [x] Instructions for how to modify Buildroot configurations and make within the docker
- [x] Description in how to connect into the container? (To check files, configurations, hashes, etc)
- [x] More...

Work in progress, but submitting as draft to get feedback

### CODE REVIEW

**Comment by DesobedienteTecnologico** [comment]
Looks good!


Regarding the file compression:
Probably adding how to decompress the **.gz** will be great for new users. Or some warning, saying that decompression file is needed? (What do you think?)


Do we probably need to think for cross-platform at all? For **.gz, .tar, .xz, etc.** Windows users would need external tools.
With **.zip** they will not.

**Comment by newtonick** [comment]
> Looks good!
> 
> Regarding the file compression: Probably adding how to decompress the **.gz** will be great for new users. Or some warning, saying that decompression file is needed? (What do you think?)
> 
> Do we probably need to think for cross-platform at all? For **.gz, .tar, .xz, etc.** Windows users would need external tools. With **.zip** they will not.

Good thoughts, how about we just remove the gzip compression completely?

**Comment by newtonick** [comment]
I went ahead in the README and removed the .gz extension on all the files.

**Comment by newtonick** [comment]
Opened PR #26 to remove gzip of the image

**Comment by DesobedienteTecnologico** [comment]
> > Looks good!
> > Regarding the file compression: Probably adding how to decompress the **.gz** will be great for new users. Or some warning, saying that decompression file is needed? (What do you think?)
> > Do we probably need to think for cross-platform at all? For **.gz, .tar, .xz, etc.** Windows users would need external tools. With **.zip** they will not.
> 
> Good thoughts, how about we just remove the gzip compression completely?

Make sense due the tiny size of the iso. Great

**Comment by DesobedienteTecnologico** [comment]
What do you think about to add:

1. The SeedSigner OS info I have in my [blog](https://desobedientetecnologico.gitlab.io/blog/posts/seedsigner_os/).
    (Probably only the Boot sequence isn't that much information without the rest)
2. Warning regarding the EEPROM PPi4 have?.

**Comment by newtonick** [comment]
> What do you think about to add:
> 
> 1. The SeedSigner OS info I have in my [blog](https://desobedientetecnologico.gitlab.io/blog/posts/seedsigner_os/).
>    (Probably only the Boot sequence isn't that much information without the rest)
> 2. Warning regarding the EEPROM PPi4 have?.

I think it would be good to add some of the information in your blog and a warning regarding the EEPROM in Pi4. We need to find a balance between being informative vs succinct.

**Comment by newtonick** [comment]
I'm done making changes for this for now unless there is something specific that needs changing. I think we can do additions as seperate PRs.

**Comment by newtonick** [comment]
I've added more to the readme like @DesobedienteTecnologico requested (Boot Sequence, OS Layers, etc). This PR is ready for review and merge.

**Pull request merged**
