### PR TITLE
RPi4 support

### PR DESCRIPTION
**Pull request by DesobedienteTecnologico**
### Configuration added for RPi4:

---

1. [X] Final users version - Mount/Umount MicroSD | **✅ Working**
3. [X] Dev version | **✅ Working**

### CODE REVIEW

**Comment by DesobedienteTecnologico** [comment]
Tested and working!
Waiting for feedback based on own compilation for Merge.

**Comment by newtonick** [comment]
@DesobedienteTecnologico camera is not working. I get this error:

PiCameraMMALError
exc.py, 184 in meal_check Failed to create MMAL component b'vc.camera_info'

To rule out hardware issues, I used seedsigner 0.5.1 image on RPiOS and the camera is working.

**Comment by newtonick** [comment]
These following changes appear to have resolved the camera issue:

git diff:

```
index d431b59..ceac8ad 100644
--- a/opt/pi4/board/genimage-rpi-seedsigner.cfg
+++ b/opt/pi4/board/genimage-rpi-seedsigner.cfg
@@ -11,7 +11,7 @@ image boot.vfat {
       "zImage"
     }
   }
-  size=41M
+  size=42M
 }

 image seedsigner_os.img {
diff --git a/opt/pi4/board/kernel.config b/opt/pi4/board/kernel.config
index c03580d..15beee6 100644
--- a/opt/pi4/board/kernel.config
+++ b/opt/pi4/board/kernel.config
@@ -166,6 +166,10 @@ CONFIG_UIO=m
 CONFIG_UIO_PDRV_GENIRQ=m
 CONFIG_STAGING=y
 CONFIG_STAGING_MEDIA=y
+CONFIG_VIDEO_RPIVID=m
+CONFIG_VIDEO_BCM2835=m
+CONFIG_VIDEO_CODEC_BCM2835=m
+CONFIG_VIDEO_ISP_BCM2835=m
 CONFIG_BCM2835_VCHIQ=y
 CONFIG_CLK_RASPBERRYPI=y
 CONFIG_MAILBOX=y
```

**Comment by DesobedienteTecnologico** [comment]
> These following changes appear to have resolved the camera issue:
> ...

Thanks for feedback. Changes added.

**Comment by newtonick** [comment]
ACK and tested

Please merge!

**Pull request merged**
