### PR TITLE
Add raspberry firmware config overlay to disable wifi and bt

### PR DESCRIPTION
**Pull request by newtonick**
This is more of a safe guard than really needed. When raspberry firmware is used these additional overlays will disable wifi and bluetooth hardware at boot through configuration of the device tree. 

https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README

### CODE REVIEW

**Comment by DesobedienteTecnologico** [comment]
Great! LGTM.

Just I saw that those where renamed:
https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README#L3078-L3093

What do you think to add the new ones? So we can keep Pi0, Pi2 and Pi4 without Pi3* references on **config.txt**

Reference for new ones: 
https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README#L895-L915

**Comment by newtonick** [comment]
> What do you think to add the new ones? So we can keep Pi0, Pi2 and Pi4 without Pi3* references on **config.txt**

Good idea. Are we pulling the master branch for firmware or a specific commit or pre-compiled binary?

**Comment by DesobedienteTecnologico** [comment]
> > What do you think to add the new ones? So we can keep Pi0, Pi2 and Pi4 without Pi3* references on **config.txt**
> 
> Good idea. Are we pulling the master branch for firmware or a specific commit or pre-compiled binary?

Right now we are getting rpi-firmware specifically this version:
https://github.com/buildroot/buildroot/blob/b634d504cb5a0b621f115f36c50a712e85fc8027/package/rpi-firmware/rpi-firmware.mk#L7
image

**Comment by DesobedienteTecnologico** [comment]
> > What do you think to add the new ones? So we can keep Pi0, Pi2 and Pi4 without Pi3* references on **config.txt**
> 
> Good idea. Are we pulling the master branch for firmware or a specific commit or pre-compiled binary?

     

Right now we are getting rpi-firmware specifically from this version:
https://github.com/buildroot/buildroot/blob/b634d504cb5a0b621f115f36c50a712e85fc8027/package/rpi-firmware/rpi-firmware.mk#L7

As you probably see here the commit match with mine. In this example I wanted to be sure it contains disable-wifi:

image

**Comment by newtonick** [comment]
> > > What do you think to add the new ones? So we can keep Pi0, Pi2 and Pi4 without Pi3* references on **config.txt**
> > 
> > 
> > Good idea. Are we pulling the master branch for firmware or a specific commit or pre-compiled binary?
> 
> Right now we are getting rpi-firmware specifically from this version: https://github.com/buildroot/buildroot/blob/b634d504cb5a0b621f115f36c50a712e85fc8027/package/rpi-firmware/rpi-firmware.mk#L7
> 
> As you probably see here the commit match with mine. In this example I wanted to be sure it contains disable-wifi:
> 
> image

Thank you, this was helpful. I could not figure out where the commit in build root was referenced.

**Comment by newtonick** [comment]
@DesobedienteTecnologico I've removed the pi3 reference and added the pi4 config. Please review when you have a chance.

**Comment by newtonick** [comment]
Do we want to include this in the 0.6.0 release?

**Comment by DesobedienteTecnologico** [comment]
> Do we want to include this in the 0.6.0 release?

Sure, we can.

**Pull request merged**
