### PR TITLE
Restructure and add Docker from DT repo

### PR DESCRIPTION
**Pull request by newtonick**
Using much of the work @DesobedienteTecnologico has done [here](https://github.com/DesobedienteTecnologico/docker_seedsigner-os) I added docker support to this repo.

Goals of this PR
- 1 repo for seedsigner-os build configuration and docker build config
- Make build script (build.sh) more flexible (works in docker and on debian linux based OS)
- 1 command and build all architecture images (docker-compose up)
- pull out as much duplicate config outside the different architecture configurations (rootfs-overlay, packages, buildroot_dl, workdir)

This is my first shot at making this happen. Still some stuff to do, but wanted to get enough working that you could see what I was attempting to accomplish. 4 builds are working. pi0, pi02w, pi0-dev, and pi02w-dev. I've tested this in native Ubuntu (without docker) and with docker-compose.

I'm starting this PR in Draft

if you run ```SS_ARGS="--help" docker-compose up``` you'll see the different build.sh script options. You can also clone the repo (following the README.md), cd into seedsigner-os/opt, and then run ./build.sh -all to build the images (in seed signer-os/images).

Notes about how I restructured:
- renamed build_workdir/builder to opt/build.sh
- moved build_workdir to output (generated by the build.sh script in the docker container or locally if used outside docker)
- docker container uses 2 volumnes (opt and images)
- compiled images are moved to images dir once created
- removed extra raspberrypi sub directory in the board directory for each config
- moved package dir out of each config dir and named external-packages
- moved rootfs-overlay out of each config dir (up one level)
- I tried to keep as much of "working dir" in the docker container (best I/O compared to volume dirs)

### CODE REVIEW

**Comment by DesobedienteTecnologico** [comment]
Tested and working fine!

Will push the future support for RPi 4 in your PR.

**Comment by eliasnaur** [comment]
I want to build seedsigner-os on my macOS M1 machine. With this PR applied, I get

```
% docker-compose up
[+] Running 1/0
 ⠿ Container seedsigner-os-build-images-1  Created                                                                                                                                                       0.0s
Attaching to seedsigner-os-build-images-1
seedsigner-os-build-images-1  | no-skip-repo
seedsigner-os-build-images-1  | cloning repo https://github.com/SeedSigner/seedsigner.git with branch 0.5.1-ram
seedsigner-os-build-images-1  | Cloning into './rootfs-overlay/opt'...
Updating files: 100% (167/167), done.ing files:  28% (48/167)
seedsigner-os-build-images-1  | make: *** No rule to make target 'pi0_defconfig'.  Stop.
seedsigner-os-build-images-1  | make: *** No targets specified and no makefile found.  Stop.
seedsigner-os-build-images-1  | /opt
seedsigner-os-build-images-1  | cloning repo https://github.com/SeedSigner/seedsigner.git with branch 0.5.1-ram
seedsigner-os-build-images-1  | Cloning into './rootfs-overlay/opt'...
Updating files: 100% (167/167), done.ing files:  28% (47/167)
seedsigner-os-build-images-1  | make: *** No rule to make target 'pi02w_defconfig'.  Stop.
seedsigner-os-build-images-1  | make: *** No targets specified and no makefile found.  Stop.
seedsigner-os-build-images-1  | /opt
seedsigner-os-build-images-1 exited with code 0
```

Do you know whether building on macOS Docker is feasible?

**Comment by newtonick** [comment]
> Do you know whether building on macOS Docker is feasible?

I'm actually using a m1 Mac mini, so it should be possible. I'll see if I can recreate the error your getting.

**Comment by DesobedienteTecnologico** [comment]
Looks like with **Docker** we can specify the platform (arch):

```bash
docker run --rm -it --platform=linux/amd64 [SSOS_NAME]
```
or
```bash
docker run --rm -it --platform=linux/x86_64 [SSOS_NAME]
```
---
Also there is a system variable that can probably help:

```bash
export DOCKER_DEFAULT_PLATFORM=linux/amd64
```
Example using it with **Docker Compose** directly:
```bash
DOCKER_DEFAULT_PLATFORM=linux/amd64 docker-compose up
```

**Comment by newtonick** [comment]
@eliasnaur I think I found your issue. You'll have to tell me what steps you performed, but this is what I did to recreate the issue I think you had and how I fixed it. Here are the commands I ran.

Check docker is installed and the version:
`docker --version`

Check docker-compose is installed and the version:
`docker-compose --version`

Recursively clone repo locally from GitHub
`git clone --recursive https://github.com/SeedSigner/seedsigner-os.git`

Move inside the locally copied repo/directory
`cd seedsigner-os`

Fetch remote PR and create local branch
`git fetch origin pull/23/head:pr_23`

Git Checkout newly created branch
`$git checkout pr_23`

At this point I get warning about the 'buildroot': Directory not empty. Here the full output of my commands above.
```
$docker --version
Docker version 20.10.21, build baeda1f
$docker-compose --version
Docker Compose version v2.12.2
$git clone --recursive https://github.com/SeedSigner/seedsigner-os.git
Cloning into 'seedsigner-os'...
remote: Enumerating objects: 402, done.
remote: Counting objects: 100% (110/110), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 402 (delta 73), reused 57 (delta 47), pack-reused 292
Receiving objects: 100% (402/402), 120.73 KiB | 1.72 MiB/s, done.
Resolving deltas: 100% (182/182), done.
Submodule 'buildroot' (https://github.com/buildroot/buildroot) registered for path 'buildroot'
Cloning into '/Users/nklockenga/tmp/seedsigner-os/buildroot'...
remote: Enumerating objects: 488751, done.        
remote: Counting objects: 100% (1205/1205), done.        
remote: Compressing objects: 100% (537/537), done.        
remote: Total 488751 (delta 706), reused 1098 (delta 666), pack-reused 487546        
Receiving objects: 100% (488751/488751), 157.11 MiB | 37.81 MiB/s, done.
Resolving deltas: 100% (322003/322003), done.
Submodule path 'buildroot': checked out 'b634d504cb5a0b621f115f36c50a712e85fc8027'
$cd seedsigner-os 
$git fetch origin pull/23/head:pr_23
remote: Enumerating objects: 251, done.
remote: Counting objects: 100% (251/251), done.
remote: Compressing objects: 100% (182/182), done.
remote: Total 248 (delta 49), reused 233 (delta 42), pack-reused 0
Receiving objects: 100% (248/248), 950.25 KiB | 5.94 MiB/s, done.
Resolving deltas: 100% (49/49), completed with 3 local objects.
From https://github.com/SeedSigner/seedsigner-os
 * [new ref]         refs/pull/23/head -> pr_23
$git checkout pr_23
warning: unable to rmdir 'buildroot': Directory not empty
Switched to branch 'pr_23'
```

If I attempted to do a docker-composer here it would fail (because opt/buildroot was not populated with the git submodule). I moved the submodule in the PR, so this requires one more additional git command to populate opt/buildroot if you did not checkout the branch I created in my repo directly. The submodule update command is:
`git submodule update --recursive`

Then, for good measure, you can delete/clean up the original buildroot directory no longer needed:
` rm -r buildroot`

Now run the build command and it should work.
`docker-compose up`

**Comment by eliasnaur** [comment]
Thank you very much, @newtonick ! My problem was updating the submodules; `docker-compose up` haven't completed yet, but seems to work as expected now.

**Comment by newtonick** [comment]
I believe this is ready to be merged. The plan is to update the README and pi4 board support as separate PR's. This one is kind of already out of hand (because of the number of file changes in the commits).

**Comment by DesobedienteTecnologico** [comment]
LGTM. Merged. 

Let's continue creating more PR with those new changes/features.

**Pull request merged**
